### Obtener todas las reservaciones
GET http://localhost:3001/reservations

### Obtener reservacion por id
GET http://localhost:3001/reservations/66ef274b52e5a5409830fe6e

### Crear una reservacion
POST http://localhost:3001/reservations
Content-Type: application/json

{
      "customer_id": "671eef6199a3dda309ee9067",
      "room_id": "66de748bc35aad3ecd5d1a9a",
      "check_in_date": "2024-10-29",
      "check_out_date": "2024-11-02"
}

### Actualizar una reservacion
PUT http://localhost:3001/reservations/66dbf097f88eec62a71a2bd9
Content-Type: application/json

{
    "status": "checked-out"
}

### Eliminar una resercacion
DELETE http://localhost:3001/reservations/66ef5deab8eca1494f1c47d3