### Obtener todas las habitaciones
GET http://localhost:3001/rooms

### Obtener habitacion por id
GET http://localhost:3001/rooms/id

### Crear habitacion
POST http://localhost:3001/rooms
Content-Type: application/json

{
    "number": 104,
    "type": "suite",
    "description": "This is room 3 has a sea view",
    "price_per_nigth": 450,
    "availability": true
}

### Actualizar habitacion
PUT http://localhost:3001/rooms/id
Content-Type: application/json

{
   "price_per_nigth": 305
}

### Eliminar habitacion
DELETE http://localhost:3001/rooms/id