### Obtener todas las habitaciones
GET http://localhost:3001/rooms/

### Obtener habitacion por id
GET http://localhost:3001/rooms/5

### Crear habitacion
POST http://localhost:3001/rooms
Content-Type: application/json

{
    "number": 209,
    "type": "individual",
    "description": "Habitación doble con cama king size y vista a la ciudad",
    "price_per_nigth": 200.00,
    "availability": true
}

### Actualizar habitacion
PUT http://localhost:3001/rooms/7
Content-Type: application/json

{
    "price_per_nigth": 130.25
}

### Eliminar habitacion
DELETE http://localhost:3001/rooms/7